### ISSUE TITLE
Make the CodeQL Github workflow use the carlspring/vertx-codeql-queries

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-vulns#15]
# Task Description

As a follow-up to carlspring/vertx-codeql-queries#1 , we need make the Github CodeQL workflow use the Vert.X query pack, so that we can test these queries against the [carlspring/vertx-vulns](https://github.com/carlspring/vertx-vulns/) code base.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Investigate the issue.
* [x] Provide a solution.
* [x] Test the fix.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:

# Resources

* [github/codeql-action/analyze](https://github.com/github/codeql-action/blob/main/analyze/action.yml)

# Useful Links

# Points of Contact

* @carlspring
