### ISSUE TITLE
When using WebClient.create, you must define WebClientOptions with an explicit setIdleTimeout

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-vulns#18]
# Task Description

When using `WebClient.create`, you must define `WebClientOptions` with an explicit `setIdleTimeout`, otherwise the TCP connections may stay open indefinitely.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [ ] Provide an example of an `Insecure` implementation.
* [ ] Provide an example of a `Secure` implementation.
* [ ] Test the fix.
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:

# Resources

# Useful Links

# Points of Contact

* @carlspring
