### ISSUE TITLE
Build a collection of typical security concern topics

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-vulns#2]
# Task Description

We need to build a collection of typical security concern topics. These will then be used to produce a list of code examples that illustrate bad and good code.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [ ] Build a collection of topics.
* [ ] Add a brief summary for each topic
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: # 
* Relates to: #

# Resources

# Useful Links

# Points of Contact
