### ISSUE TITLE
Use of tokens without expiration

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-vulns#7]
# Task Description

Add examples of tokens without expiration. Some ideas:
* `OAuth2WebClient` establishing an HTTP connection without setting a `leeway` for the expiration of the token via the `OAuth2WebClientOptions`.
* `OAuth2WebClient` establishing an HTTP connection without setting a timeout for the token request via the `OAuth2WebClientOptions`.

Check [here](https://vertx.io/docs/vertx-web-client/java/#_oauth2_security) for example configuration code.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] `OAuth2WebClient` establishing an HTTP connection without setting a `leeway` for the expiration of the token via the `OAuth2WebClientOptions`.
* [x] `OAuth2WebClient` establishing an HTTP connection without setting a timeout for the token request via the `OAuth2WebClientOptions`.
* [x] Ilustrate a secure implementation.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
  * #2 
* Depends on:
* Is a follow-up of: 
* Relates to:

# Resources

# Useful Links

* [Vert.x Examples: OAuth Security](https://vertx.io/docs/vertx-web-client/java/#_oauth2_security)

# Points of Contact

* @carlspring

**Comment by carlspring** [comment]
Implemented in [22ac40b73faba5beeaf4d751c620e15717677051].
