### ISSUE TITLE
Cross-origin resource sharing (CORS) misconfigurations

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-vulns#8]
# Task Description

Add examples of tokens without expiration. Some ideas:
* CORS configuration trusting all hosts via a wildcard configuration.
* CORS configuration trusting a specific host over an insecure HTTP connection.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Illustrate an insecure CORS configuration trusting all hosts via a wildcard configuration.
* [x] Illustrate an insecure CORS configuration trusting a specific host over an insecure HTTP connection.
* [x] Illustrate a secure CORS configuration.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
  * #2 
* Depends on:
* Is a follow-up of: 
* Relates to:

# Resources

# Useful Links

* [Vert.x Examples](https://vertx.io/docs/vertx-web-client/java/)

# Points of Contact

* @carlspring
